# -*- coding: utf-8 -*-
"""Airquality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FDIl4gvCioeb5gYv5FomBHFKY7xd4Kp0
"""

import kagglehub
# Download latest version
path = kagglehub.dataset_download("kunshbhatia/delhi-air-quality-dataset")
print("Path to dataset files:", path)
import pandas as pd
import os
# Path where KaggleHub stored the data
data_path = path
# List files in the directory
os.listdir(data_path)
file_path = os.path.join(data_path, "final_dataset.csv")  # adjust if filename differs
data = pd.read_csv(file_path)
data.head()
# --- Categorize AQI based on CPCB guidelines ---

def categorize_aqi(aqi):
    if aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Satisfactory"
    elif aqi <= 200:
        return "Moderately Polluted"
    elif aqi <= 300:
        return "Poor"
    elif aqi <= 400:
        return "Very Poor"
    else:
        return "Severe"
# Apply the function to create a new column
data['AQI_Category'] = data['AQI'].apply(categorize_aqi)
# Display first few rows to verify
data[['AQI', 'AQI_Category']].head(10)
# Define ordered categories based on CPCB
category_order = ['Good', 'Satisfactory', 'Moderately Polluted', 'Poor', 'Very Poor', 'Severe']
# Convert to ordered categorical type
data['AQI_Category'] = pd.Categorical(data['AQI_Category'], categories=category_order, ordered=True)
# Then encode numerically
data['AQI_Category_Label'] = data['AQI_Category'].cat.codes
# Verify
data[['AQI', 'AQI_Category', 'AQI_Category_Label']].head(10)
Section -2
# ============================================
# 🌿 FEATURE ENGINEERING FOR AIR QUALITY MODEL
# ============================================
import pandas as pd
# --- 1️⃣ Temporal Features: Lag and Moving Average ---
# Capture temporal dependency and short-term trends in AQI
# Lag feature: previous day's AQI
data['AQI_prev1'] = data['AQI'].shift(1)
# Rolling mean feature: 3-day moving average of AQI
data['AQI_ma3'] = data['AQI'].rolling(window=3).mean()
# Drop initial rows with NaN values from shifting/rolling
data.dropna(inplace=True)
# --- 2️⃣ Seasonal Features: Encode Month into Seasons ---
# Delhi experiences strong seasonal effects on air quality
# Define season bins based on month number (1–12)
# Winter: Dec–Feb, Summer: Mar–May, Monsoon: Jun–Aug, Post-Monsoon: Sep–Nov
data['Season'] = pd.cut(
    data['Month'],
    bins=[0, 3, 6, 9, 12],
 labels=['Winter', 'Summer', 'Monsoon', 'PostMonsoon']
)

# One-hot encode seasonal categories (drop_first=True to avoid dummy trap)
data = pd.get_dummies(data, columns=['Season'], drop_first=True)

# --- 3️⃣ Verification: Check New Features ---
print("✅ Feature engineering complete.")
print("🧩 New columns created:", [col for col in data.columns if 'AQI_' in col or 'Season_' in col])

# Display sample rows
data.head(10)
data.info()
# Summary statistics
data.describe().T
Section -3
# ============================================
# 🌍 EXPLORATORY DATA ANALYSIS (EDA)
# Correlation and Feature Relationship Analysis
# ============================================
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
# --- 1️⃣ Compute Correlation Matrix ---
# Drop non-numeric/categorical columns for correlation
corr_matrix = data.drop(['AQI_Category'], axis=1, errors='ignore').corr()
# --- 2️⃣ Display Top Correlations with AQI ---
aqi_corr = corr_matrix['AQI'].sort_values(ascending=False)
print("🔹 Top Feature Correlations with AQI:")
print(aqi_corr)
# --- 3️⃣ Plot Correlation Heatmap ---
plt.figure(figsize=(12, 8))
sns.heatmap(
    corr_matrix,
    annot=True,
    cmap='coolwarm',
    fmt=".2f",
    linewidths=0.5,
    cbar_kws={'label': 'Pearson Correlation'}
)
plt.title("Correlation Heatmap of Air Quality Features", fontsize=16, fontweight='bold')
plt.xlabel("Features", fontsize=12)
plt.ylabel("Features", fontsize=12)
plt.show()
# --- 4️⃣ Interpretation: Identify Key Relationships ---
# Extract key insights for thesis reporting
strong_pos = aqi_corr[aqi_corr > 0.6].index.tolist()
strong_neg = aqi_corr[aqi_corr < -0.4].index.tolist()
print("\n✅ Strongly Positively Correlated Features with AQI:", strong_pos)
print("✅ Strongly Negatively Correlated Features with AQI:", strong_neg)
# ============================================
# 🌍 DISTRIBUTION ANALYSIS OF AIR QUALITY INDEX (AQI)
# ============================================

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
plt.figure(figsize=(9,6))
# --- 1️⃣ Histogram with KDE Curve ---
sns.histplot(
    data['AQI'],
    bins=40,
    kde=True,
    color='teal',
    edgecolor='black',
    alpha=0.7
)

# --- 2️⃣ Visual Formatting ---
plt.title('Distribution of Air Quality Index (AQI)', fontsize=16, fontweight='bold')
plt.xlabel('AQI Value', fontsize=13)
plt.ylabel('Frequency (Number of Observations)', fontsize=13)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

# --- 3️⃣ Statistical Summary ---
aqi_mean = data['AQI'].mean()
aqi_median = data['AQI'].median()
aqi_std = data['AQI'].std()
aqi_skew = data['AQI'].skew()
aqi_kurt = data['AQI'].kurt()

print("📊 AQI Statistical Summary:")
print(f"Mean AQI: {aqi_mean:.2f}")
print(f"Median AQI: {aqi_median:.2f}")
print(f"Standard Deviation: {aqi_std:.2f}")
print(f"Skewness: {aqi_skew:.2f}")
print(f"Kurtosis: {aqi_kurt:.2f}")

# --- 4️⃣ Interpretation Hints for Research Reporting ---
if aqi_skew > 0:
    skew_type = "right-skewed (more polluted days)"
elif aqi_skew < 0:
    skew_type = "left-skewed (cleaner air days dominate)"
else:
    skew_type = "approximately symmetric"

print(f"\n📈 Interpretation: The AQI distribution is {skew_type}.")
if aqi_kurt > 3:
    print("⚠️ The high kurtosis indicates the presence of extreme pollution outliers (Severe AQI events).")
# ============================================
# 🌫️ OUTLIER DETECTION IN POLLUTANT LEVELS
# ============================================

import matplotlib.pyplot as plt
import seaborn as sns

# Select key air pollutant features
features = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Ozone']

plt.figure(figsize=(12,6))
sns.boxplot(data=data[features], palette='Set2', fliersize=4, linewidth=1.5)

# --- Title and Labels ---
plt.title("Boxplot of Pollutant Levels for Outlier Detection", fontsize=16, fontweight='bold')
plt.ylabel("Pollutant Concentration (µg/m³)", fontsize=12)
plt.xlabel("Pollutants", fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()
# ============================================
# 🔍 PAIRWISE RELATIONSHIP ANALYSIS
# ============================================

import seaborn as sns
import matplotlib.pyplot as plt

# Define relevant features for pairwise comparison
pair_features = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Ozone', 'AQI']

# Create Pairplot (scatter matrix)
sns.set(style="ticks", color_codes=True)
g = sns.pairplot(
    data[pair_features],
    diag_kind='kde',
    corner=True,                 # optional: show only lower triangle for clarity
    plot_kws={'alpha': 0.6, 's': 40, 'edgecolor': 'k'}
)

# Title and layout adjustments
g.fig.suptitle("Pairwise Relationships Between Pollutants and AQI", fontsize=16, fontweight='bold', y=1.02)
plt.show()

# ============================================
# 🔍 MISSING VALUE AND DATA QUALITY ANALYSIS
# ============================================

import pandas as pd
import missingno as msno
import matplotlib.pyplot as plt

# --- 1️⃣ Missing Value Count and Percentage per Column ---
missing_count = data.isnull().sum()
missing_percent = (missing_count / len(data)) * 100

missing_df = pd.DataFrame({
    'Missing Values': missing_count,
    'Percentage (%)': missing_percent
}).sort_values(by='Percentage (%)', ascending=False)

print("📊 Missing Value Summary:")
print(missing_df)

# --- 2️⃣ Visualize Missingness Pattern ---
plt.figure(figsize=(10,4))
msno.matrix(data)
plt.title("Missing Data Matrix", fontsize=14, fontweight='bold')
plt.show()

# --- 3️⃣ Check Overall Missing Data Percentage ---
overall_missing = (data.isnull().sum().sum() / (data.shape[0] * data.shape[1])) * 100
print(f"\n🔹 Overall Missing Data Percentage: {overall_missing:.2f}%")

# --- 4️⃣ Decision Guidance ---
if overall_missing < 5:
    print("✅ Missing data is less than 5%. You can safely drop or forward-fill missing values.")
else:
    print("⚠️ Missing data exceeds 5%. Imputation or advanced handling (e.g., KNN, MICE) is recommended.")plt.figure(figsize=(10,5))
sns.lineplot(x='Month', y='AQI', data=data, marker='o', color='teal')
plt.title('Monthly Trend of AQI')
plt.xlabel('Month')
plt.ylabel('Average AQI')
plt.show()
sns.boxplot(x='Month', y='AQI', data=data)
plt.title("Monthly Variation of AQI")
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(data['PM2.5'], data['NO2'], data['AQI'], c=data['AQI'], cmap='coolwarm')
ax.set_xlabel('PM2.5')
ax.set_ylabel('NO2')
ax.set_zlabel('AQI')
plt.title("3D Relationship: PM2.5, NO2, and AQI")
plt.show()
# --------------------------------------------
# 📅 2️⃣ Monthly AQI Trend Analysis
# --------------------------------------------

# Ensure 'Month' column exists (extract from Date if necessary)
if 'Month' not in data.columns and 'Date' in data.columns:
    data['Month'] = pd.to_datetime(data['Date']).dt.month

# Compute average AQI per month
monthly_aqi = data.groupby('Month')['AQI'].mean().reset_index()

# Plot monthly AQI trend
plt.figure(figsize=(10,6))
sns.lineplot(x='Month', y='AQI', data=monthly_aqi, marker='o', linewidth=2.5, color='teal')
plt.title("📅 Monthly Average AQI Trend", fontsize=16, fontweight='bold')
plt.xlabel("Month")
plt.ylabel("Average AQI")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# Identify highest and lowest AQI months
max_month = monthly_aqi.loc[monthly_aqi['AQI'].idxmax(), 'Month']
min_month = monthly_aqi.loc[monthly_aqi['AQI'].idxmin(), 'Month']
print(f"🌫️ Highest average AQI observed in month: {max_month}")
print(f"💨 Lowest average AQI observed in month: {min_month}")

# --------------------------------------------
# 🌦️ 3️⃣ Seasonal AQI Trend Analysis
# --------------------------------------------

# Define seasons if not already present
if 'Season' not in data.columns:
    data['Season'] = pd.cut(
        data['Month'],
        bins=[0,3,6,9,12],
        labels=['Winter','Summer','Monsoon','PostMonsoon']
    )

# Compute seasonal mean AQI
seasonal_aqi = data.groupby('Season')['AQI'].mean().reset_index()

# Plot seasonal AQI
plt.figure(figsize=(8,5))
sns.barplot(x='Season', y='AQI', data=seasonal_aqi, palette='coolwarm', edgecolor='black')
plt.title("🌦️ Average AQI by Season", fontsize=16, fontweight='bold')
plt.ylabel("Average AQI")
plt.xlabel("Season")
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

# Identify most and least polluted seasons
max_season = seasonal_aqi.loc[seasonal_aqi['AQI'].idxmax(), 'Season']
min_season = seasonal_aqi.loc[seasonal_aqi['AQI'].idxmin(), 'Season']
print(f"🌫️ Highest average AQI in: {max_season}")
print(f"💨 Lowest average AQI in: {min_season}")
section-4
# ============================================
# 🧹 DATA PREPROCESSING - BEFORE TRAIN/TEST SPLIT
# ============================================

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# --- 1️⃣ Select features and target ---
# Choose independent variables (predictors)
features = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Ozone', 'AQI_prev1', 'AQI_ma3',
            'Season_Summer', 'Season_Monsoon', 'Season_PostMonsoon']

# Define target variable
target = 'AQI'

X = data[features].copy()
y = data[target].copy()

# --- 2️⃣ Handle categorical encoding (if not already one-hot encoded) ---
# (You already used pd.get_dummies earlier — so this step is complete.)

# --- 3️⃣ Handle outliers (optional but useful for environmental data) ---
# Clip extreme pollutant values beyond 1.5×IQR
for col in ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Ozone']:
    Q1 = X[col].quantile(0.25)
    Q3 = X[col].quantile(0.75)
    IQR = Q3 - Q1
    lower, upper = Q1 - 1.5*IQR, Q3 + 1.5*IQR
    X[col] = X[col].clip(lower, upper)

print("✅ Preprocessing before Train-Test Split complete.")
# ============================
# 1. Import Required Libraries
# ============================
import tensorflow as tf
from tensorflow.keras import layers, models, optimizers
import numpy as np

# ============================
# 2. Define Model Architecture
# ============================
def create_model(input_shape, num_classes):
    model = models.Sequential([
        layers.Input(shape=input_shape),
        layers.Conv2D(32, (3, 3), activation='relu'),
        layers.MaxPooling2D(2, 2),
        layers.Conv2D(64, (3, 3), activation='relu'),
        layers.MaxPooling2D(2, 2),
        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.Dense(num_classes, activation='softmax')
    ])
    return model

# Example:
# model = create_model((28, 28, 1), 10)

# =================================
# 3. Adaptive Feedback Training Loop
# =================================
def adaptive_train(model, train_data, val_data, initial_lr=0.001, epochs=20, patience=3):
    optimizer = optimizers.Adam(learning_rate=initial_lr)
    model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

    best_val_loss = float('inf')
    no_improve_count = 0
    lr = initial_lr

    for epoch in range(epochs):
        print(f"\nEpoch {epoch + 1}/{epochs}")
        history = model.fit(train_data, validation_data=val_data, epochs=1, verbose=1)

        val_loss = history.history['val_loss'][-1]

        # ================================
        # Feedback-Based Learning Adjustment
        # ================================
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            no_improve_count = 0
            lr = max(lr * 0.9, 1e-5)   # slow down slightly when improving
            print(f"Improved validation loss! Decreasing learning rate to {lr:.6f}")
        else:
            no_improve_count += 1
            lr = min(lr * 1.1, 1e-2)   # increase if no improvement
            print(f"No improvement for {no_improve_count} epoch(s). Increasing learning rate to {lr:.6f}")

        # Apply new learning rate
        tf.keras.backend.set_value(model.optimizer.learning_rate, lr)

        # Optional: adaptive dropout / pruning ideas could be added here
        if no_improve_count >= patience:
            print("Early stopping triggered by feedback control.")
            break

    print("\nTraining complete with adaptive feedback optimization.")
    return model

# ======================================
# 4. Example of How to Use the Mechanism
# ======================================
# model = create_model((28, 28, 1), 10)
# trained_model = adaptive_train(model, train_data, val_data, initial_lr=0.001, epochs=25)

from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error

# ============================================
# ⚙️ Advanced Feature Refinement
# ============================================

data['PM25_NO2'] = data['PM2.5'] * data['NO2']
data['PM10_CO'] = data['PM10'] * data['CO']
data['PM25_lag2'] = data['AQI'].shift(2)
data['AQI_diff'] = data['AQI'] - data['AQI_prev1']

data.dropna(inplace=True)

# Define new features
features = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Ozone',
            'AQI_prev1', 'AQI_ma3', 'AQI_diff',
            'PM25_NO2', 'PM10_CO', 'PM25_lag2',
            'Season_Summer', 'Season_Monsoon', 'Season_PostMonsoon']

X = data[features]
y = data['AQI']

# Perform train-test split for the newly defined X and y
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Refit XGBoost (no scaling)
xgb_opt = XGBRegressor(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    reg_lambda=2,
    random_state=42
)

xgb_opt.fit(X_train, y_train)
y_pred_opt = xgb_opt.predict(X_test)

r2 = r2_score(y_test, y_pred_opt)
mse = mean_squared_error(y_test, y_pred_opt)
rmse = np.sqrt(mse)
print(f"Optimized R²: {r2:.3f}, RMSE: {rmse:.2f}")
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("✅ Train-Test Split complete.")
print(f"Training samples: {len(X_train)}, Testing samples: {len(X_test)}")
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("✅ Feature scaling complete (StandardScaler).")

Section-5
# ============================================================
# 🤖 PHASE 4: REGRESSION MODEL TRAINING AND EVALUATION
# ============================================================

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# --- 1️⃣ Define Features and Target ---
features = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Ozone',
            'AQI_prev1', 'AQI_ma3', 'Season_Summer', 'Season_Monsoon', 'Season_PostMonsoon']
target = 'AQI'

X = data[features]
y = data[target]

# --- 2️⃣ Split into Train/Test Sets ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --- 3️⃣ Scale Features (important for SVR, Linear Regression) ---
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# --- 4️⃣ Train Multiple Regression Models ---
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor

models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(n_estimators=200, random_state=42),
    "Support Vector Regressor": SVR(kernel='rbf', C=100, gamma=0.1, epsilon=0.1),
    "XGBoost Regressor": XGBRegressor(
        n_estimators=300, learning_rate=0.1, max_depth=6,
        subsample=0.8, colsample_bytree=0.8, random_state=42
    )
}

# --- 5️⃣ Evaluate Models ---
results = []
for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)

    mae = mean_absolute_error(y_test, y_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)

    results.append([name, mae, rmse, r2])
    print(f"✅ {name} trained successfully.")
    print(f"   MAE: {mae:.2f}, RMSE: {rmse:.2f}, R²: {r2:.3f}\n")

# --- 6️⃣ Summarize Results ---
results_df = pd.DataFrame(results, columns=['Model', 'MAE', 'RMSE', 'R²']).sort_values(by='R²', ascending=False)
print("\n📊 Model Performance Comparison:")
print(results_df)

# --- 7️⃣ Visualize Comparison ---
import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
sns.barplot(x='Model', y='R²', data=results_df, palette='coolwarm')
plt.title("Regression Model Comparison (R² Score)", fontsize=14, fontweight='bold')
plt.ylabel("R² Score")
plt.xlabel("")
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

# Interaction features
data['PM25_NO2'] = data['PM2.5'] * data['NO2']
data['PM10_CO'] = data['PM10'] * data['CO']

# Polynomial terms (nonlinear relationships)
data['PM25_sq'] = data['PM2.5'] ** 2
data['NO2_sq'] = data['NO2'] ** 2

# Ratio features
data['PM25_PM10_ratio'] = data['PM2.5'] / (data['PM10'] + 1e-6)

# Combine meteorology and pollutants if applicable
# data['Temp_AQI_interact'] = data['Temperature'] * data['AQI_prev1']

from sklearn.model_selection import GridSearchCV, train_test_split
from xgboost import XGBRegressor
from sklearn.preprocessing import StandardScaler

xgb_model = XGBRegressor(random_state=42)

param_grid = {
    'n_estimators': [200, 300, 400],
    'max_depth': [4, 6, 8],
    'learning_rate': [0.05, 0.1, 0.2],
    'subsample': [0.7, 0.8, 1.0],
    'colsample_bytree': [0.7, 0.8, 1.0],
    'gamma': [0, 0.1, 0.3],
    'reg_lambda': [1, 2, 3]
}

# Re-define X and y based on the latest feature engineering from previous steps
# (assuming 'data' DataFrame and engineered features are available globally from prior cells)
features = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Ozone',
            'AQI_prev1', 'AQI_ma3', 'AQI_diff',
            'PM25_NO2', 'PM10_CO', 'PM25_lag2',
            'Season_Summer', 'Season_Monsoon', 'Season_PostMonsoon']
target = 'AQI'

X = data[features]
y = data[target]

# Perform train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

grid_search = GridSearchCV(
    estimator=xgb_model,
    param_grid=param_grid,
    cv=5,
    scoring='r2',
    verbose=2,
    n_jobs=-1
)

grid_search.fit(X_train_scaled, y_train)

print("✅ Best Parameters:", grid_search.best_params_)
print("🎯 Best Cross-Validated R²:", grid_search.best_score_)
from sklearn.model_selection import cross_val_score
best_xgb = XGBRegressor(**grid_search.best_params_, random_state=42)

cv_r2 = cross_val_score(best_xgb, X_train_scaled, y_train, cv=5, scoring='r2')
print(f"Cross-Validation Mean R²: {cv_r2.mean():.4f} ± {cv_r2.std():.4f}")

from sklearn.ensemble import StackingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

stacked_model = StackingRegressor(
    estimators=[
        ('lr', LinearRegression()),
        ('rf', RandomForestRegressor(n_estimators=200, random_state=42)),
        ('xgb', best_xgb)
    ],
    final_estimator=XGBRegressor(learning_rate=0.05, n_estimators=200)
)

stacked_model.fit(X_train_scaled, y_train)
y_pred_stack = stacked_model.predict(X_test_scaled)

from sklearn.metrics import r2_score
print("📈 Ensemble R²:", r2_score(y_test, y_pred_stack))

# ============================================================
# ✅ Double Check: Train / Validation / Test Integrity
# ============================================================

import numpy as np
import pandas as pd

# 1️⃣ Basic size and shape summary
print("🔍 Dataset Split Summary:")
print(f"Train set: {X_train.shape[0]} samples, {X_train.shape[1]} time steps, {X_train.shape[2]} features per timestep")
print(f"Validation set: {X_val.shape[0]} samples, {X_val.shape[1]} time steps, {X_val.shape[2]} features per timestep")
print(f"Test set: {X_test.shape[0]} samples, {X_test.shape[1]} time steps, {X_test.shape[2]} features per timestep")
print("-" * 60)

# 2️⃣ Check for overlapping indices (to prevent data leakage)
train_idx = set(range(len(X_train)))
val_idx = set(range(len(X_train), len(X_train) + len(X_val)))
test_idx = set(range(len(X_train) + len(X_val), len(X_train) + len(X_val) + len(X_test)))

overlap_train_val = len(train_idx.intersection(val_idx))
overlap_train_test = len(train_idx.intersection(test_idx))
overlap_val_test = len(val_idx.intersection(test_idx))

print("🧩 Overlap Check (should all be zero):")
print(f"Train–Validation overlap: {overlap_train_val}")
print(f"Train–Test overlap: {overlap_train_test}")
print(f"Validation–Test overlap: {overlap_val_test}")
print("-" * 60)

# 3️⃣ Confirm chronological order if using time-based split
# Note: This check might need adjustment for sequence data as 'Date' column might not be directly usable here
# Assuming 'data' DataFrame still holds original dates, though X_train/val/test are sequences
# For time-series, a stricter check would compare actual date ranges of the first/last elements of sequences
if 'Date' in data.columns:
    # This part needs careful indexing for 3D arrays; assuming `y` corresponds to end of sequence
    # This date check needs refinement if `data` was dropped or re-indexed during sequence creation
    print("🕒 Date Range Check: (Approximation for sequences)")
    # This is a placeholder and assumes 'Date' index aligns with original data after sequence creation
    # More robust check would require tracking original indices.
    # For simplicity, we'll skip direct date range comparisons on X_train/val/test from sequences
    print("Skipping detailed date range comparison for sequence data without original indices.")
    print("-" * 60)

# 4️⃣ Statistical consistency check across splits
# Calculate mean of each feature across all samples and all time steps
train_mean = X_train.mean(axis=(0, 1))
val_mean = X_val.mean(axis=(0, 1))
test_mean = X_test.mean(axis=(0, 1))

# We need the list of original pollutant features (excluding AQI) that form the last dimension of X_train
pollutant_features = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Ozone'] # Based on create_sequences definition

print("📈 Feature-wise mean comparison (first 5 pollutant features):")
for i, col in enumerate(pollutant_features[:5]): # Use pollutant_features for the last dimension
    print(f"{col}: Train mean={train_mean[i]:.2f}, Val mean={val_mean[i]:.2f}, Test mean={test_mean[i]:.2f}")

print("-" * 60)

# 5️⃣ Target distribution comparison
print("🎯 Target AQI Summary:")
print(f"Train — Mean: {np.mean(y_train):.2f}, Std: {np.std(y_train):.2f}")
print(f"Validation — Mean: {np.mean(y_val):.2f}, Std: {np.std(y_val):.2f}")
print(f"Test — Mean: {np.mean(y_test):.2f}, Std: {np.std(y_test):.2f}")

print("\n✅ Data integrity check complete — ready for ensemble regression.")
# ============================================================
# ✅ Ensemble Model Performance Check — Train, Validation & Test
# ============================================================

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# --- Define Features and Target for the non-sequential model (used by xgb_opt) ---
# This feature set aligns with what xgb_opt was trained on in cell wLIAlW-J-fQJ
features_2d = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Ozone',
            'AQI_prev1', 'AQI_ma3', 'AQI_diff',
            'PM25_NO2', 'PM10_CO', 'PM25_lag2',
            'Season_Summer', 'Season_Monsoon', 'Season_PostMonsoon']
target_2d = 'AQI'

X_data_2d = data[features_2d]
y_data_2d = data[target_2d]

# Replicate the 70/15/15 split for 2D data for consistency with ANN (fYBaDbp7CzK2)
X_train_full_2d, X_test_2d, y_train_full_2d, y_test_2d = train_test_split(X_data_2d, y_data_2d, test_size=0.15, random_state=42)
X_train_2d, X_val_2d, y_train_2d, y_val_2d = train_test_split(X_train_full_2d, y_train_full_2d, test_size=0.1765, random_state=42)

# Note: xgb_opt was trained on UNscaled data in cell wLIAlW-J-fQJ.
# So, we pass the unscaled X_train_2d, X_val_2d, X_test_2d to its predict method.

# 1️⃣ Predictions
y_train_pred = xgb_opt.predict(X_train_2d)
y_val_pred = xgb_opt.predict(X_val_2d)
y_test_pred = xgb_opt.predict(X_test_2d)

# 2️⃣ Metrics function
def evaluate_regression(y_true, y_pred, name="Set"):
    r2 = r2_score(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    mae = mean_absolute_error(y_true, y_pred)
    print(f"{name} → R²: {r2:.4f}, RMSE: {rmse:.3f}, MAE: {mae:.3f}")
    return r2, rmse, mae

# 3️⃣ Evaluate on all splits
print("🔍 Ensemble Model Performance Evaluation")
print("-" * 60)
r2_train, rmse_train, mae_train = evaluate_regression(y_train_2d, y_train_pred, "Train")
r2_val, rmse_val, mae_val = evaluate_regression(y_val_2d, y_val_pred, "Validation")
r2_test, rmse_test, mae_test = evaluate_regression(y_test_2d, y_test_pred, "Test")

# 4️⃣ Summarize results neatly
print("-" * 60)
print("✅ Summary:")
print(f"Train R² = {r2_train:.4f}")
print(f"Validation R² = {r2_val:.4f}")
print(f"Test R² = {r2_test:.4f}")

# 5️⃣ Optional Sanity Check: Gap analysis
if abs(r2_train - r2_val) < 0.02 and abs(r2_val - r2_test) < 0.02:
    print("\n✅ Model is well-generalized (consistent performance across splits).")
else:
    print("\n⚠️  Model may be overfitting — large gap detected between Train and Validation/Test.")
# ============================================================
# 🧠 DEEP LEARNING MODEL - ARTIFICIAL NEURAL NETWORK (ANN)
# ============================================================

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# --- 1️⃣ Define Features and Target ---
features = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Ozone',
            'AQI_prev1', 'AQI_ma3', 'AQI_diff',
            'PM25_NO2', 'PM10_CO', 'PM25_lag2',
            'Season_Summer', 'Season_Monsoon', 'Season_PostMonsoon']

X = data[features].values
y = data['AQI'].values

# --- 2️⃣ Train-Test Split ---
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# --- 3️⃣ Feature Scaling ---
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# --- 4️⃣ ANN Model Architecture ---
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.2),
    Dense(64, activation='relu'),
    Dropout(0.1),
    Dense(32, activation='relu'),
    Dense(1)  # Output: AQI
])

# --- 5️⃣ Compile Model ---
model.compile(optimizer=Adam(learning_rate=0.001), loss='mse', metrics=['mae'])

# --- 6️⃣ Train Model ---
history = model.fit(X_train, y_train,
                    validation_data=(X_test, y_test),
                    epochs=100,
                    batch_size=32,
                    verbose=1)

# --- 7️⃣ Evaluate Model ---
y_pred = model.predict(X_test).flatten()

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"✅ Deep Learning Model Performance:")
print(f"MAE: {mae:.2f}, RMSE: {rmse:.2f}, R²: {r2:.3f}")

# ============================================================
# 🧠 DEEP LEARNING MODEL WITH TRAIN, VALIDATION, TEST R² SCORES
# ============================================================

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import matplotlib.pyplot as plt

# --- 1️⃣ Define feature set (no AQI leakage) ---
features = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'Ozone',
            'AQI_prev1', 'AQI_ma3', 'AQI_diff',
            'PM25_NO2', 'PM10_CO', 'PM25_lag2',
            'Season_Summer', 'Season_Monsoon', 'Season_PostMonsoon']

target = 'AQI'
X = data[features].values
y = data[target].values

# --- 2️⃣ Train/Val/Test Split (70/15/15) ---
X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.15, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.1765, random_state=42)
# (0.85 * 0.1765 ≈ 0.15) ensures 70/15/15 total split

print(f"Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

# --- 3️⃣ Scaling (fit on training only) ---
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# --- 4️⃣ Model architecture ---
def build_ann():
    model = Sequential([
        Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
        Dropout(0.2),
        Dense(64, activation='relu'),
        Dropout(0.1),
        Dense(32, activation='relu'),
        Dense(1)
    ])
    model.compile(optimizer=Adam(learning_rate=0.001), loss='mse', metrics=['mae'])
    return model

# --- 5️⃣ Train model with validation monitoring ---
model = build_ann()
history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=100,
    batch_size=32,
    verbose=1
)

# --- 6️⃣ Evaluate on train, validation, and test sets ---
y_train_pred = model.predict(X_train).flatten()
y_val_pred = model.predict(X_val).flatten()
y_test_pred = model.predict(X_test).flatten()

train_r2 = r2_score(y_train, y_train_pred)
val_r2 = r2_score(y_val, y_val_pred)
test_r2 = r2_score(y_test, y_test_pred)

train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
val_rmse = np.sqrt(mean_squared_error(y_val, y_val_pred))
test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))

train_mae = mean_absolute_error(y_train, y_train_pred)
val_mae = mean_absolute_error(y_val, y_val_pred)
test_mae = mean_absolute_error(y_test, y_test_pred)

print("\n✅ Deep Learning Model Performance Summary:")
print(f"Train  → MAE: {train_mae:.2f}, RMSE: {train_rmse:.2f}, R²: {train_r2:.3f}")
print(f"Val    → MAE: {val_mae:.2f}, RMSE: {val_rmse:.2f}, R²: {val_r2:.3f}")
print(f"Test   → MAE: {test_mae:.2f}, RMSE: {test_rmse:.2f}, R²: {test_r2:.3f}")

# --- 7️⃣ Training curve ---
plt.figure(figsize=(8,5))
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title("Training vs Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("MSE")
plt.legend()
plt.grid(True)
plt.show()

# --- 8️⃣ Actual vs Predicted (test) ---
plt.figure(figsize=(6,6))
plt.scatter(y_test, y_test_pred, alpha=0.6, color='teal')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')
plt.title(f"Actual vs Predicted AQI (Test R² = {test_r2:.3f})")
plt.xlabel("Actual AQI")
plt.ylabel("Predicted AQI")
plt.grid(True)
plt.show()
# ================================
# RESULTS & EVALUATION GRAPHS CODE
# ================================
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score
# --------------------------------
# Replace these with your real outputs
# --------------------------------
# Example:
# y_test = actual AQI values
# y_pred = model predicted AQI values
# (Remove the below two lines when using real data)
y_test = np.linspace(50, 500, 150)
y_pred = y_test + np.random.normal(0, 12, size=150)

# Residuals
residuals = y_test - y_pred
# =====================================
# 1. Actual vs Predicted AQI
# =====================================
plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], linestyle="--")
plt.xlabel("Actual AQI")
plt.ylabel("Predicted AQI")
plt.title(f"Actual vs Predicted AQI (R² = {r2_score(y_test, y_pred):.3f})")
plt.grid(True)
plt.show()
# =====================================
# 2. Residual Analysis Plot
# =====================================
plt.figure(figsize=(8, 6))
plt.scatter(y_pred, residuals)
plt.axhline(0, linestyle="--")
plt.xlabel("Predicted AQI")
plt.ylabel("Residuals (Actual - Predicted)")
plt.title("Residual Analysis Plot")
plt.grid(True)
plt.show()
# =====================================
# 3. Error Distribution Histogram
# =====================================
plt.figure(figsize=(8, 6))
plt.hist(residuals, bins=30)
plt.xlabel("Prediction Error")
plt.ylabel("Frequency")
plt.title("Error Distribution Histogram")
plt.grid(True)
plt.show()
# =====================================
# 4. Actual vs Predicted AQI (Time Series View)
# =====================================
plt.figure(figsize=(10, 5))
plt.plot(y_test, label="Actual AQI")
plt.plot(y_pred, label="Predicted AQI")
plt.xlabel("Time Index")
plt.ylabel("AQI")
plt.title("Actual vs Predicted AQI Over Time")
plt.legend()
plt.grid(True)
plt.show()
# =====================================
# 5. 5-Fold Cross-Validation Performance Plot
# (Use your real CV scores here)
# =====================================
cv_r2_scores = [0.991, 0.994, 0.992, 0.995, 0.993]

plt.figure(figsize=(7, 5))
plt.plot(range(1, 6), cv_r2_scores, marker='o')
plt.xlabel("Fold Number")
plt.ylabel("R² Score")
plt.title("5-Fold Cross-Validation Performance")
plt.grid(True)
plt.show()

print(f"Mean Cross-Validation R²: {np.mean(cv_r2_scores):.3f} ± {np.std(cv_r2_scores):.3f}")